version: "3.7"
services:
  tibdoc_devnodejs:
    container_name: tibdoc_nodejs
    image: node:16-bullseye
    environment:
      DEV: 1
      TIMEZONE: Indian/Reunion
    volumes:
      - ./tibillet:/documentation
    working_dir: /documentation
    command: "bash /documentation/dev.sh"
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.tibdoc_devnodejs.tls.certresolver=tlsresolver
      - traefik.http.routers.tibdoc_devnodejs.entrypoints=websecure
      - traefik.http.routers.tibdoc_devnodejs.rule=Host(`doc.mike.codecommun.re`)
      - traefik.http.services.tibdoc_devnodejs.loadbalancer.server.port=3000

    networks:
      - frontend

networks:
  frontend:
    external: true


